---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    jf_version: '2.122.0'

  pre_tasks:
    - name: Check if jf downloaded
      stat:
        path: "/usr/local/bin/jf"
      register: jf_check

    - name: Check if jf executes
      shell: "/usr/local/bin/jf --version | grep {{ jf_version }}"
      register: jf_installed

  tasks:
    - name: Check that jf exists
      assert:
        that: jf_check.stat.exists

    - name: Check jf installed and version is correct
      assert:
        that: jf_installed.rc == 0
